import { FormEvent, useEffect, useState } from 'react'

const api = import.meta.env.VITE_API_URL ?? 'http://localhost:8000'
type Documento = { id:string; nome_arquivo:string; status:string }
type Fonte = { document:string; page:number|null }

function cabecalhos(){ return { Authorization:`Bearer ${sessionStorage.getItem('noctua_token')}` } }

export default function App(){
 const[cadastro,setCadastro]=useState(false),[autenticado,setAutenticado]=useState(Boolean(sessionStorage.getItem('noctua_token'))),[modo,setModo]=useState<'enviar'|'perguntar'>('enviar'),[erro,setErro]=useState(''),[documentos,setDocumentos]=useState<Documento[]>([]),[arquivo,setArquivo]=useState<File|null>(null),[pergunta,setPergunta]=useState(''),[resposta,setResposta]=useState(''),[fontes,setFontes]=useState<Fonte[]>([]),[carregando,setCarregando]=useState(false)
 async function carregar(){try{const r=await fetch(`${api}/documents`,{headers:cabecalhos()});const j=await r.json();if(!r.ok)throw Error(j.detail);setDocumentos(j)}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar documentos.')}}
 useEffect(()=>{if(autenticado) void carregar()},[autenticado])
 async function entrar(e:FormEvent<HTMLFormElement>){e.preventDefault();setErro('');const f=new FormData(e.currentTarget),b=cadastro?{nome_organizacao:f.get('organizacao'),email:f.get('email'),senha:f.get('senha')}:{email:f.get('email'),senha:f.get('senha')};try{const r=await fetch(`${api}${cadastro?'/auth/register':'/auth/login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),j=await r.json();if(!r.ok)throw Error(j.detail);sessionStorage.setItem('noctua_token',j.access_token);setAutenticado(true)}catch(e){setErro(e instanceof Error?e.message:'Não foi possível conectar à API.')}}
 async function enviarArquivo(){if(!arquivo)return;setCarregando(true);setErro('');const f=new FormData();f.append('arquivo',arquivo);try{const r=await fetch(`${api}/documents`,{method:'POST',headers:cabecalhos(),body:f}),j=await r.json();if(!r.ok)throw Error(j.detail);setArquivo(null);await carregar()}catch(e){setErro(e instanceof Error?e.message:'Falha no envio.')}finally{setCarregando(false)}}
 async function perguntar(){if(!pergunta.trim())return;setCarregando(true);setErro('');try{const r=await fetch(`${api}/chat`,{method:'POST',headers:{...cabecalhos(),'Content-Type':'application/json'},body:JSON.stringify({question:pergunta})}),j=await r.json();if(!r.ok)throw Error(j.detail);setResposta(j.answer);setFontes(j.sources)}catch(e){setErro(e instanceof Error?e.message:'Falha ao consultar a base.')}finally{setCarregando(false)}}
 if(autenticado)return <main className="dashboard"><header><div className="logo">◉ NOCTUA</div><button className="sair" onClick={()=>{sessionStorage.removeItem('noctua_token');setAutenticado(false)}}>Sair</button></header><div className="cabecalho-dashboard"><p className="etiqueta">BASE DE CONHECIMENTO</p><h1>Seu conhecimento, organizado.</h1></div><nav className="acoes"><button className={modo==='enviar'?'ativo':''} onClick={()=>setModo('enviar')}>↑ Enviar documento</button><button className={modo==='perguntar'?'ativo':''} onClick={()=>setModo('perguntar')}>◌ Perguntar</button></nav><section className="painel-dashboard">{modo==='enviar'?<><h2>Envie um documento</h2><input type="file" accept=".pdf,.txt" onChange={e=>setArquivo(e.target.files?.[0]??null)}/><button className="principal" disabled={!arquivo||carregando} onClick={enviarArquivo}>{carregando?'Enviando…':'Enviar arquivo'}</button></>:<><h2>Faça uma pergunta</h2><div className="campo-chat"><input value={pergunta} onChange={e=>setPergunta(e.target.value)} placeholder="Pergunte algo sobre seus documentos"/><button onClick={perguntar} disabled={carregando}>↑</button></div>{resposta&&<><p>{resposta}</p><small>{fontes.map(f=>`${f.document}${f.page?` · página ${f.page}`:''}`).join(' | ')}</small></>}</>}</section><section className="documentos"><h2>Documentos da organização</h2>{documentos.length?documentos.map(d=><p key={d.id}>{d.nome_arquivo} — {d.status}</p>):<p>Nenhum documento enviado.</p>}</section>{erro&&<small>{erro}</small>}</main>
  return <main className="pagina"><section className="marca"><div className="logo">◉ NOCTUA</div><div className="texto-marca"><p>BASE DE CONHECIMENTO INTELIGENTE</p><h1>Conhecimento seguro,<br/>perto de você.</h1><span>Centralize documentos e encontre respostas fundamentadas nas fontes da sua organização.</span></div><b>+</b></section><section className="acesso"><div className="cartao"><p className="etiqueta">PORTAL NOCTUA</p><h2>{cadastro?'Crie sua conta':'Boas-vindas de volta'}</h2><div className="abas"><button className={!cadastro?'ativo':''} onClick={()=>setCadastro(false)}>Entrar</button><button className={cadastro?'ativo':''} onClick={()=>setCadastro(true)}>Criar conta</button></div><form onSubmit={entrar}>{cadastro&&<label>Organização<input name="organizacao" required placeholder="Ex.: Noctua Tecnologia"/></label>}<label>E-mail<input name="email" type="email" required placeholder="voce@organizacao.com"/></label><label>Senha<input name="senha" type="password" minLength={8} required placeholder="Mínimo de 8 caracteres"/></label><button className="principal">{cadastro?'Criar conta':'Entrar no Noctua'}</button></form>{erro&&<small>{erro}</small>}</div></section></main>
}
